default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks: # see ./README.md#Pre-Commit Hooks for descriptions of what these hooks do
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
        args: [-b, main]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: Format build Python files with Python Black
        language_version: python3
        args: [--line-length=80]
  - repo: local
    hooks:
      - id: bazel-buildifier-fmt
        name: Format and lint Bazel BUILD files
        description: Runs the "buildifier" tool to format and lint Bazel BUILD files for consistency.
        entry: dev/pre-commit/bazel_buildifier_fmt.sh
        language: script
        files: (WORKSPACE|.*BUILD(\.bazel)?)$
      - id: go-fmt
        name: Format Go files
        description: Runs the "gofmt" tool to format Go source code for consistency.
        entry: dev/pre-commit/go_fmt.sh
        language: script
        files: ^.*\.(go)$
