repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: pretty-format-json
      - id: detect-private-key
      - id: detect-aws-credentials
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
  -   repo: https://github.com/ambv/black
      rev: stable
      hooks:
      - id: black
        args: [--line-length=80]
        language_version: python3.8
